name: "matlab-buildtool"

runs:

  using: "composite"

  steps:

  - name: Check Matlab Syntax
    if: ${{ matrix.release >= 'R2023b' }}
    uses: matlab-actions/run-build@v2
    with:
      tasks: check

  - name: Test Matlab Code
    if: ${{ matrix.release >= 'R2023b' }}
    uses: matlab-actions/run-build@v2
    with:
      tasks: test
