name: ci

on:
  push:
    paths:
    - "**.m"
    - ".github/workflows/ci.yml"


jobs:

  matlab:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    strategy:
      matrix:
        release: [R2020b, latest]

    steps:
    - uses: actions/checkout@v4

    - uses: ./.github/workflows/composite-install-matlab

    - uses: ./.github/workflows/composite-buildtool
