name: ci

on:
  push:
    paths:
    - "**.m"
    - ".github/workflows/ci.yml"

# avoid wasted runs
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  matlab:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    strategy:
      matrix:
        release: [R2023b, R2025b]

    steps:
    - uses: actions/checkout@v6

    - uses: ./.github/workflows/composite-install-matlab

    - uses: ./.github/workflows/composite-buildtool
